#!/bin/bash
#	hooks/pre-commit  3.311.778  2019-07-26T15:24:54.721125-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.310  
#	   pre-commit add logging information to output #57 
#	hooks/pre-commit  3.310.777  2019-07-26T15:19:17.281992-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.309  
#	   add script name and PID to echo statement #57 
#	hooks/pre-commit  3.308.775  2019-07-26T15:04:20.488675-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.307  
#	   added commiter to message when run #57 
#	hooks/pre-commit  3.307.774  2019-07-26T14:59:48.012839-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.306  
#	   completed creating ${WORKING_DIRECTORY}/hooks/FILE_LIST of commited files pre commit #57 
###
### production standard 3.0 shellcheck
### production standard 5.1.160 Copyright
#       Copyright (c) 2019 Bradley Allen
#       MIT License is in the online DOCUMENTATION
###
#       Date and time function ISO 8601
get_date_stamp() {
DATE_STAMP=$(date +%Y-%m-%dT%H:%M:%S.%6N%:z)
TEMP=$(date +%Z)
DATE_STAMP="${DATE_STAMP} (${TEMP})"
}

#       Fully qualified domain name FQDN hostname
LOCALHOST=$(hostname -f)
###
WORKING_DIRECTORY=$(git rev-parse --show-toplevel)
echo -e "${DATE_STAMP} ${LOCALHOST} ${0}[$$] Create ${WORKING_DIRECTORY}/hooks/FILE_LIST file of files that are being commited by ${GIT_AUTHOR_NAME}."
git status -s --untracked-files=no | grep -v '^D  ' | awk '{print $2}' > "${WORKING_DIRECTORY}"/hooks/FILE_LIST
