#!/bin/bash
#	hooks/pre-commit  3.371.839  2019-07-27T16:46:28.845919-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.370  
#	   testing .git/hooks/pre-commit 
#	hooks/pre-commit  3.370.838  2019-07-27T16:42:23.978542-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.369  
#	   testing .git/hooks/pre-commit 
#	hooks/pre-commit  3.367.835  2019-07-27T16:09:08.644492-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.366  
#	   testing .git/hooks/pre-post-commit FVT 
#	hooks/pre-commit  3.366.834  2019-07-27T15:52:06.518083-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.365-1-g0b2e3c6  
#	   testing .git/hooks/pre/post-commti 
#	hooks/pre-commit  3.363.830  2019-07-27T12:23:11.837447-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.362  
#	   add BOLD to putout 
#	hooks/pre-commit  3.312.779  2019-07-26T15:28:59.979867-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.311  
#	   pre-commit add logging information to output / corrected incident with function not being call #57 
#	hooks/pre-commit  3.307.774  2019-07-26T14:59:48.012839-05:00 (CDT)  https://github.com/BradleyA/docker-security-infrastructure  uadmin  six-rpi3b.cptx86.com 3.306  
#	   completed creating ${WORKING_DIRECTORY}/hooks/COMMIT_FILE_LIST of commited files pre commit #57 
###
### production standard 3.0 shellcheck
### production standard 5.1.160 Copyright
#       Copyright (c) 2019 Bradley Allen
#       MIT License is in the online DOCUMENTATION
###
BOLD=$(tput -Txterm bold)
NORMAL=$(tput -Txterm sgr0)
#       Date and time function ISO 8601
DATE_STAMP=$(date +%Y-%m-%dT%H:%M:%S.%6N%:z)
TEMP=$(date +%Z)
DATE_STAMP="${DATE_STAMP} (${TEMP})"
#       Fully qualified domain name FQDN hostname
LOCALHOST=$(hostname -f)
###
WORKING_DIRECTORY=$(git rev-parse --show-toplevel)
### >>>	do  ${WORKING_DIRECTORY}/hooks/ exist and is it writable I hope so is not go enough .. <<<
echo -e "${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${LINENO}  ${BOLD}Creating ${WORKING_DIRECTORY}/hooks/COMMIT_FILE_LIST file with files being commited${NORMAL} for ${GIT_AUTHOR_NAME} (${USER})."
git status -s --untracked-files=no | grep -v '^D  ' | awk '{print $2}' > "${WORKING_DIRECTORY}"/hooks/COMMIT_FILE_LIST
