#!/bin/bash
#	create-site-private-public-tls	3.1	2017-12-19_15:43:01_CST uadmin rpi3b-two.cptx86.com
#	Adding version number
# %W% %G% %U%
#	set -x
#	set -v
#
#	Create the CA Private Key
#		
NUMBERDAYS=1460
#
mkdir -pv  $HOME/.docker/docker-ca/.private
chmod 0700 $HOME/.docker/docker-ca/.private
cd         $HOME/.docker/docker-ca/.private
#
echo -e "\n>>	Creating private key with passphrase"
openssl genrsa -aes256 -out ca-priv-key.pem 4096
chmod 0400 $HOME/.docker/docker-ca/.private/ca-priv-key.pem
echo -e "\nOnce all the certificates and keys have been generated with this private key,"
echo "it would be prudent to move the private key to a Universal Serial Bus (USB) memory stick."
echo "Remove the private key from the system and store the USB memory stick in a locked"
echo -e "fireproof location.\n"
echo ">>	Creating public key"
echo -e "\nThe public key is copied to all systems in an environment so that those systems"
echo "trust signed certificates."
echo "The following is a list of prompts from the following command and example answers are"
echo "in parentheses."
echo "Country Name (US)"
echo "State or Province Name (Texas)"
echo "Locality Name (Cedar Park)"
echo "Organization Name (Company Name)"
echo "Organizational Unit Name (IT)"
echo "Common Name (two.cptx86.com)"
echo -e "Email Address ()\n"
cd         $HOME/.docker/docker-ca
openssl req -x509 -days $NUMBERDAYS -sha256 -new -key .private/ca-priv-key.pem -out ca.pem
chmod 0444 ca.pem
echo -e "\n\n	These certificate are valid for $NUMBERDAYS days.\n"
echo "It would be prudent to document the date when to renew these certificate and set"
echo "an operations or project management calendar entry about 15 days before renewal as"
echo "a reminder to schedule a new site certificate."




